title: WebUSB Debug
description: A simple tool to test WebUSB compatible devices

baseurl: "/webusb-debug"


markdown: GFM
remote_theme: pages-themes/primer@v0.2.0

sass:
  style: compressed
  sass_dir: styles

plugins:
  - jekyll-remote-theme
